// Ordered painting manifest — order matches the source design's FILES array,
// so index-based picks (hero/feature images, "No. NN" labels) line up.
const PAINTINGS = [
  { src: 'assets/paintings/painting-01.jpg' },
  { src: 'assets/paintings/painting-02.jpg' },
  { src: 'assets/paintings/painting-03.jpg' },
  { src: 'assets/paintings/painting-04.jpg' },
  { src: 'assets/paintings/painting-05.jpg' },
  { src: 'assets/paintings/painting-06.jpg' },
  { src: 'assets/paintings/painting-07.jpg' },
  { src: 'assets/paintings/painting-08.jpg' },
  { src: 'assets/paintings/painting-09.jpg' },
  { src: 'assets/paintings/painting-10.jpg' },
  { src: 'assets/paintings/painting-11.jpg' },
  { src: 'assets/paintings/painting-12.jpg' },
  { src: 'assets/paintings/painting-13.jpg' },
  { src: 'assets/paintings/painting-14.jpg' },
  { src: 'assets/paintings/painting-15.jpg' },
  { src: 'assets/paintings/painting-16.jpg' },
  { src: 'assets/paintings/painting-17.jpg' },
  { src: 'assets/paintings/painting-18.jpg' },
  { src: 'assets/paintings/painting-19.jpg' },
  { src: 'assets/paintings/painting-20.jpg' },
  { src: 'assets/paintings/painting-21.jpg' },
  { src: 'assets/paintings/painting-22.jpg' },
  { src: 'assets/paintings/painting-23.jpg' },
  { src: 'assets/paintings/painting-24.jpg' },
];
