// Ordered painting manifest — order matches the source design's FILES array,
// so index-based picks (hero/feature images, "No. NN" labels) line up.
// Swap `src` for a real photo (any format) once available; everything else
// keeps working unchanged.
const PAINTINGS = [
  { src: 'assets/paintings/painting-01.svg' },
  { src: 'assets/paintings/painting-02.svg' },
  { src: 'assets/paintings/painting-03.svg' },
  { src: 'assets/paintings/painting-04.svg' },
  { src: 'assets/paintings/painting-05.svg' },
  { src: 'assets/paintings/painting-06.svg' },
  { src: 'assets/paintings/painting-07.svg' },
  { src: 'assets/paintings/painting-08.svg' },
  { src: 'assets/paintings/painting-09.svg' },
  { src: 'assets/paintings/painting-10.svg' },
  { src: 'assets/paintings/painting-11.svg' },
  { src: 'assets/paintings/painting-12.svg' },
  { src: 'assets/paintings/painting-13.svg' },
  { src: 'assets/paintings/painting-14.svg' },
  { src: 'assets/paintings/painting-15.svg' },
  { src: 'assets/paintings/painting-16.svg' },
  { src: 'assets/paintings/painting-17.svg' },
  { src: 'assets/paintings/painting-18.svg' },
  { src: 'assets/paintings/painting-19.svg' },
  { src: 'assets/paintings/painting-20.svg' },
  { src: 'assets/paintings/painting-21.svg' },
  { src: 'assets/paintings/painting-22.svg' },
  { src: 'assets/paintings/painting-23.svg' },
  { src: 'assets/paintings/painting-24.svg' },
];
